### ISSUE TITLE
Type Error:argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by chenyan1123** [Jittor/JNeRF#33]
Loading config from:  ./projects/ngp/configs/ngp_base.py
load train data
Traceback (most recent call last):
  File "/home/featurize/JNeRF/python/jnerf/utils/registry.py", line 33, in build_from_cfg
    module = obj_cls(**args)
  File "/home/featurize/JNeRF/python/jnerf/dataset/dataset.py", line 111, in __init__
    self.load_data()
  File "/home/featurize/JNeRF/python/jnerf/dataset/dataset.py", line 150, in load_data
    if 'h' in json_data:
TypeError: argument of type 'NoneType' is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/featurize/JNeRF/tools/run_net.py", line 54, in <module>
    main()
  File "/home/featurize/JNeRF/tools/run_net.py", line 44, in main
    runner = Runner()
  File "/home/featurize/JNeRF/python/jnerf/runner/runner.py", line 24, in __init__
    self.dataset["train"]   = build_from_cfg(self.cfg.dataset.train, DATASETS)
  File "/home/featurize/JNeRF/python/jnerf/utils/registry.py", line 37, in build_from_cfg
    raise TypeError(e)
TypeError: <class 'jnerf.dataset.dataset.NerfDataset'>.argument of type 'NoneType' is not iterable

could you help me?

**Comment by bluefacej** [comment]
me too，anyone can help?

**Comment by kwea123** [comment]
You need to change this
https://github.com/Jittor/JNeRF/blob/a6f419b6ab24fcfe0f2ea7fc6ca37c9cc1fc2294/projects/ngp/configs/ngp_base.py#L39
to where the folder is located, did you?
