### ISSUE TITLE
Mac M1系统运行文件报错

### ISSUE THREAD

**Issue by cjp-chu** [Jittor/JNeRF#49]
![Uploading image.png…]()

**Comment by cjp-chu** [comment]
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Users/achu/Desktop/JNeRF-master/python/jnerf/runner/runner.py
[i 0927 15:33:15.946090 32 compiler.py:955] Jittor(1.3.5.16) src: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor
[i 0927 15:33:15.994051 32 compiler.py:956] g++ at /usr/bin/g++(13.1.6)
[i 0927 15:33:15.994188 32 compiler.py:957] cache_path: /Users/achu/.cache/jittor/jt1.3.5/g++13.1.6/py3.8.8/macOS-10.16-x8xb9/AppleM1Pro/default
ld: library not found for -lomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "/Users/achu/Desktop/JNeRF-master/python/jnerf/runner/runner.py", line 2, in <module>
    import jittor as jt
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor/compiler.py", line 1180, in <module>
    check_cache_compile()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor/compiler.py", line 884, in check_cache_compile
    recompile = compile(cc_path, cc_flags+f" {opt_flags} ", files, jit_utils.cache_path+'/jit_utils_core'+extension_suffix, True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor/compiler.py", line 126, in compile
    return do_compile(fix_cl_flags(cmd))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor/compiler.py", line 91, in do_compile
    run_cmd(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor_utils/__init__.py", line 188, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: "/usr/bin/g++" "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor/src/utils/cache_compile.cc" "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor/src/utils/log.cc" "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor/src/utils/tracer.cc" "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc" "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor/src/utils/str_utils.cc"   -Wall -Wno-unknown-pragmas -std=c++14 -fPIC  -march=native  -fdiagnostics-color=always  -lstdc++ -ldl -shared -undefined dynamic_lookup -lomp  -I"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jittor/src" -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8  -O2   -o "/Users/achu/.cache/jittor/jt1.3.5/g++13.1.6/py3.8.8/macOS-10.16-x8xb9/AppleM1Pro/default/jit_utils_core.cpython-38-darwin.so"

Process finished with exit code 1
