### ISSUE TITLE
有关import jnerf的问题

### ISSUE THREAD

**Issue by chenyan1123** [Jittor/JNeRF#55]
你好，我已经安装jittor，且可以运行example 可是我import jnerf 却出现错误
(/cloud/conda) ➜  work python
Python 3.9.12 (main, Jun  1 2022, 11:38:51)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jnerf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'jnerf'
请问如何解决

**Comment by chenyan1123** [comment]
然后运行 python tools/run_net.py --config-file ./projects/ngp/configs/ngp_base.py这一步就会报错：Traceback (most recent call last):
  File "/home/featurize/work/JNeRF/tools/run_net.py", line 7, in <module>
    from jnerf.runner import Runner,NeuSRunner
ModuleNotFoundError: No module named 'jnerf'

**Comment by Jittor** [comment]
请问您有按照readme里面的安装脚本，运行pip install吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月26日(周三) 晚上9:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Jittor/JNeRF] 有关import jnerf的问题 (Issue #55)




 
然后运行 python tools/run_net.py --config-file ./projects/ngp/configs/ngp_base.py这一步就会报错：Traceback (most recent call last):
 File "/home/featurize/work/JNeRF/tools/run_net.py", line 7, in 
 from jnerf.runner import Runner,NeuSRunner
 ModuleNotFoundError: No module named 'jnerf'
